labels:
  - name: 'Type: Question'
    labeled:
      issue:
        body: |-
          Hello @{{ sender.login }},
          
          We sadly do not provide support through Issues.
          Please join the [Discord Server](https://discord.gg/6dazXp6) and ask in the `#javabotblockapi` channel to receive support.
          *This issue has been automatically closed.*
        action: close
  - name: 'Type: Duplicate'
    labeled:
      issue:
        body: |-
          Your issue is already known and a separate issue with the exact same report/feature request already exist.
          
          Please comment on the already existing issue with your information instead of opening your own.
          *This issue has been automatically closed.*
        action: close
  - name: 'Type: JDA issue'
    labeled:
      issue:
        body: |-
          Hello @{{ sender.login }}
          
          The issue you encounter is caused by JDA and not JavaBotBlockAPI.
          Please [join the JDA Discord](https://discord.gg/0hMr4ce0tIk3pSjp) and ask there for support.
          *This issue has been automatically closed.*
  - name: 'Type: BotBlock issue'
    labeled:
      issue:
        body: |-
          Hello @{{ sender.login }}
          
          The issue you encounter is caused by BotBlock and not JavaBotBlockAPI.
          Please [join the BotBlock Discord](https://botblock.org/discord) and ask there for support.
          *This issue has been automatically closed.*
  - name: 'Result: Invalid'
    labeled:
      issue:
        body: |-
          Hello @{{ sender.login }},
          
          Your Issue has beeen marked as invalid.
          Make sure to use and follow the provided Issue templates. Issues not following the templates get closed.
        action: close
      pr:
        body: |-
          Hello @{{ sender.login }},
          
          Your Pull request has beeen marked as invalid.
          Make sure to use and follow the provided Pull request templates. Pull requests not following the templates get closed.
        action: close
    unlabeled:
      issue:
        body: |-
          Thank you @{{ sender.login }} for following the Issue Template.
          Your Issue has been re-opened and the dev will look into it.
        action: open
      pr:
        body: |-
          Thank you @{{ sender.login }} for following the Pull request Template.
          Your Pull request has been re-opened and the dev will look into it.
        action: open
  - name: 'Status: Requires more info'
    labeled:
      issue:
        body: |-
          Hello @{{ sender.login }},
          
          Your issue doesn't provide enough information for us to help you.  
          Please make sure to provide as much information as possible, including the version of JavaBotBlockAPI, any configuration you made and what steps you took.
    unlabeled:
      issue:
        body: |-
          Thank you @{{ sender.login }} for providing additional information.
          The developer will take a look at your issue and try to find a solution for it, so stay tight.
