site_name: JavaBotBlockAPI Wiki
site_description: 'Official Wiki of JavaBotBlockAPI'
site_author: 'Andre_601'
site_url: 'https://docs.botblock.org/JavaBotBlockAPI'

docs_dir: docs/
site_dir: '../docs/'

copyright: |
  &copy; 2019-2020 Andreas Schmidt (Andre_601)
  
repo_name: 'botblock/JavaBotBlockAPI'
repo_url: 'https://github.com/botblock/JavaBotBlockAPI'
edit_uri: '/edit/master/wiki'

nav:
  - Welcome: index.md
  - Changelog: wiki/changelog.md
  - Methods:
    - Methods: wiki/methods/index.md
    - BotBlockAPI: wiki/methods/botblockapi.md
    - GetBotAction: wiki/methods/get/getbotaction.md
    - GetListAction: wiki/methods/get/getlistaction.md
    - PostAction: wiki/methods/post/postaction.md
  - Deprecated:
    - Deprecated: wiki/deprecated/index.md
    - GetAction: wiki/deprecated/getaction.md
    - RequestHandler: wiki/deprecated/requesthandler.md
  - Javadoc: 'https://docs.botblock.org/JavaBotBlockAPI/javadoc/'

theme:
  name: 'material'
  custom_dir: 'theme'
  logo: 'assets/img/logo.png'
  favicon: 'assets/img/logo.png'
  palette:
    primary: 'blue'
    accent: 'cyan'
  features:
  - tabs
  icon:
    repo: 'octicons/repo'

extra:
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/botblock/JavaBotBlockAPI'

extra_css:
- 'assets/css/dark.css'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
