blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.gg/6dazXp6
    about: Join my Discord for receiving faster support.
  - name: Javadoc
    url: https://jbba.dev/docs
    about: Check the Javadocs for additional information.
  - name: CI Server
    url: https://ci.codemc.io/job/botblock/job/JavaBotBlockAPI/
    about: You can find development builds on our CI Server.
  - name: Releases
    url: https://bintray.com/andre601/maven/JavaBotBlockAPI
    about: Latest releases can be found on Bintray.
