name: Rebase Action

on:
  issues:
    types:
    - labeled
    - unlabeled
  pull_request:
    types:
    - labeled
    - unlabeled

jobs:
  rebase:
    name: Auto Comment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.2
        with:
          ref: master
      - name: Comment on (un)labeled issue/Pull request
        uses: peaceiris/actions-label-commenter@v1.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
