name: Building Documentation

on:
  push:
    branches:
      - master
    paths:
      - 'wiki/**'
      - '!wiki/README.md'

jobs:
  build_wiki:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools
        python -m pip install -r requirements.txt
    - name: Build pages
      working-directory: './wiki'
      run: |
        mkdocs build
    # Build Javadoc
    - uses: actions/checkout@v2
    - name: Setup Java 8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build Javadoc
      run: |
        ./gradlew javadoc
    - name: Push changes
      run: |
        git config --global user.name "github-actiosn[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        
        git add -A
        git commit -m "Updating Documentation"
        git push
