name: Publication task

on:
  release:
    types: [published]
    branches:
    - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Publish (Bintray)
      env:
        bintrayUser: ${{ secrets.bintrayUsername }}
        bintrayApiKey: ${{ secrets.bintrayApiKey }}
        BUILD_NUMBER: 0 # Releases are always major.minor.revision_0
      run: ./gradlew bintrayUpload
  sendMessage:
    if: success()
    runs-on: ubuntu-latest
    steps:
    - name: Discord notification
      uses: rjstone/discord-webhook-notify@v1.0.2
      with:
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
        severity: info
        username: New release
        description: '**Release Information**'
        details: ''
