name: Rebase Action

on:
  issue_comment:
    types: [created]

jobs:
  rebase:
    name: Rebase
    runs-on: [ubuntu-latest]
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase')
    steps:
      - uses: actions/checkout@master
      - name: Auto Rebase
        uses: cirrus-actions/rebase@1.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  always-run:
    needs: [rebase]
    name: Always run
    runs-on: [ubuntu-latest]
    steps:
      - name: Perform Echo
        run: echo "Used to prevent Action to show as failed."
