name: Publication task

on:
  release:
    types: [published]
    branches:
    - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Publish (Bintray)
      id: publish_bintray
      env:
        bintrayUser: ${{ secrets.bintrayUsername }}
        bintrayApiKey: ${{ secrets.bintrayApiKey }}
      run: ./gradlew bintrayUpload
    #- name: Publish (GitHub Packages)
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #  run: ./gradlew publish
    - name: Zip files
      working-directory: ./build/libs
      run: zip release-${{ github.event.release.tag_name }} *.jar
    - name: Upload to release
      uses: AButler/upload-release-assets@v2.0
      with:
        files: 'build/libs/release-${{ github.event.release.tag_name }}.zip;build/libs/*.jar'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
  sendMessage:
    needs: [publish]
    if: success()
    runs-on: ubuntu-latest
    steps:
    - name: Discord notification
      uses: rjstone/discord-webhook-notify@v1
      with:
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
        severity: info
        avatarUrl: 'https://raw.githubusercontent.com/botblock/JavaBotBlockAPI/master/src/main/resources/Jbba.png'
        username: 'New release (${{ github.event.release.tag_name }})'
        text: '${{ github.event.release.name }}'
        description: '[**Release Information**](${{ github.event.release.html_url }})'
        details: '${{ github.event.release.body }}'
        footer: 'Version ${{github.event.release.tag_name}}'
