name: Update Wiki

on:
  push:
    paths:
      - 'wiki/**'
    tags-ignore:
      - '**'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Update wiki
        uses: docker://decathlon/wiki-page-creator-action:latest
        env:
          ACTION_MAIL: ${{ secrets.EMAIL }}
          ACTION_NAME: Andre601
          GH_PAT: ${{ secrets.GH_PAT }}
          MD_FOLDER: wiki
          OWNER: botblock
          REPO_NAME: JavaBotBlockAPI
          SKIP_MD: README.md
